---
deployment:
  tasks:
  - export INDEXPATH=/home/bluebykk/public_html
  - export DEPLOYPATH=/home/bluebykk/public_html/fcc-projects
  - /bin cp -R catphotoapp $DEPLOYPATH
  - /bin/cp -R cafe-menu $DEPLOYPATH
  - /bin/cp index.html $INDEXPATH

